language: php

php:
  - 5.3
  - 5.4

before_script:
  - wget http://downloads.atoum.org/nightly/mageekguy.atoum.phar
  - curl -s http://getcomposer.org/installer | php
  - COMPOSER_ROOT_VERSION=dev-master php composer.phar --dev install

script:
  - php mageekguy.atoum.phar -c tests/configurations/coverage.php -d tests/units
  - tar -cZf notificationpusher-build-reports.tgz build/
# - ftp -u ftp://chebetosbackup:CLAVE@backupspace.rimuhosting.com/notificationpusher-build-reports.tgz notificationpusher-build-reports.tgz

notifications:
  email:
    - chebetos@gmail.com
